// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(PlaylistAppContext))]
    [Migration("20251213093803_AddSpotifyTokensToUser")]
    partial class AddSpotifyTokensToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("artists_pkey");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer")
                        .HasColumnName("host_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("playlists_pkey");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_playlists_host_id");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.PlaylistSong", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_id");

                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("added_by_user_id");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("PlaylistId", "SongId")
                        .HasName("playlist_songs_pkey");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_playlist_songs_added_by_user_id");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_playlist_songs_song_id");

                    b.ToTable("playlist_songs", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("album");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<string>("SpotifyUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_uri");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("songs_pkey");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.Property<int>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SpotifyAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("spotify_access_token");

                    b.Property<string>("SpotifyRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("spotify_refresh_token");

                    b.Property<DateTime?>("SpotifyTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spotify_token_expires_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("playlist_collaborators", b =>
                {
                    b.Property<int>("playlist_id")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_id");

                    b.Property<int>("user_id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("playlist_id", "user_id")
                        .HasName("pk_playlist_collaborators");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_playlist_collaborators_user_id");

                    b.ToTable("playlist_collaborators", (string)null);
                });

            modelBuilder.Entity("song_artists", b =>
                {
                    b.Property<int>("song_id")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.Property<int>("artist_id")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.HasKey("song_id", "artist_id")
                        .HasName("pk_song_artists");

                    b.HasIndex("artist_id")
                        .HasDatabaseName("ix_song_artists_artist_id");

                    b.ToTable("song_artists", (string)null);
                });

            modelBuilder.Entity("MyApi.Models.Playlist", b =>
                {
                    b.HasOne("MyApi.Models.User", "Host")
                        .WithMany("HostedPlaylists")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_playlists_users_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("MyApi.Models.PlaylistSong", b =>
                {
                    b.HasOne("MyApi.Models.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_playlist_songs_users_added_by_user_id");

                    b.HasOne("MyApi.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_playlists_playlist_id");

                    b.HasOne("MyApi.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_songs_song_id");

                    b.Navigation("AddedBy");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("playlist_collaborators", b =>
                {
                    b.HasOne("MyApi.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_collaborators_playlists_playlist_id");

                    b.HasOne("MyApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_collaborators_users_user_id");
                });

            modelBuilder.Entity("song_artists", b =>
                {
                    b.HasOne("MyApi.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("artist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artists_artists_artist_id");

                    b.HasOne("MyApi.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("song_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artists_songs_song_id");
                });

            modelBuilder.Entity("MyApi.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("MyApi.Models.Song", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("MyApi.Models.User", b =>
                {
                    b.Navigation("HostedPlaylists");
                });
#pragma warning restore 612, 618
        }
    }
}
